### ISSUE TITLE
Fix styling

### ISSUE THREAD

**Issue by wernersbacher** [jrie/pi-analyze#1]
Moin,
der Content dürfte ruhig höher sein :)
Ein Design ohne floating, dafür mit flex boxes wäre durchaus zeitgemäßer.

**Comment by jrie** [comment]
@wernersbacher ich habe die Anzahl der Stellen auf 50.000 angehoben, von Initial 10.000 stellen. Auch wird im Layout jetzt marginal Flex genutzt und floats sind komplett entfernt, da alles über % Angaben geregelt wird.
